---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
    app.quarkus.io/build-timestamp: 2022-05-10 - 04:53:13 +0000
  labels:
    app.kubernetes.io/name: event-bus-processor
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: event-bus-processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-bus-processor-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: event-bus-processor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-bus-processor-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: event-bus-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
    app.quarkus.io/build-timestamp: 2022-05-10 - 04:53:13 +0000
  labels:
    app.kubernetes.io/name: event-bus-processor
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: event-bus-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: event-bus-processor
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
        app.quarkus.io/build-timestamp: 2022-05-10 - 04:53:13 +0000
      labels:
        app.kubernetes.io/name: event-bus-processor
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  key: kafka-broker
                  name: kafka
          image: sreenubk/event-bus-processor:1.0-SN5
          imagePullPolicy: Always
          name: event-bus-processor
      serviceAccountName: event-bus-processor
