---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
    app.quarkus.io/build-timestamp: 2022-05-09 - 20:02:25 +0000
  labels:
    app.kubernetes.io/name: event-bus-viewer
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: event-bus-viewer
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: event-bus-viewer
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
    app.quarkus.io/build-timestamp: 2022-05-09 - 20:02:25 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: event-bus-viewer
  name: event-bus-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/name: event-bus-viewer
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
        app.quarkus.io/build-timestamp: 2022-05-09 - 20:02:25 +0000
      labels:
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: event-bus-viewer
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: sreenubk/event-bus-viewer:1.0-SN1
          imagePullPolicy: Always
          name: event-bus-viewer
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
