---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
    app.quarkus.io/build-timestamp: 2022-05-09 - 19:36:26 +0000
  labels:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: event-bus-processor
  name: event-bus-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/name: event-bus-processor
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: f857deece8b675072567d93335728c8f1e2f2c13
        app.quarkus.io/build-timestamp: 2022-05-09 - 19:36:26 +0000
      labels:
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: event-bus-processor
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: sreenubk/event-bus-processor:1.0-SN4
          imagePullPolicy: Always
          name: event-bus-processor
